### ISSUE TITLE
Minor incompatibility with Reserved Item Slots

### ISSUE THREAD

**Issue by Re-VelatoR** [AndreyMrovol/LethalOrbitRecharge#1]
Battery operated items in reserved slots from the ReservedItemSlots mod series are not initially considered by this mod. The workaround is to drop the battery operated items in those slots on the ground before entering orbit, after which they will be targeted for recharge even in the reserved slots for the rest of the session. Minor issue, but one worth reporting.

**Comment by AndreyMrovol** [comment]
Hey, thanks for reporting the issue - I'll look into it

**Comment by AndreyMrovol** [comment]
Hey, from what i've found ReservedItemSlots slots are not considered "inventory slots" by the game due to the way they're implemented - I'll look into ways to target those **without** depending on ReservedItemsSlots, which this mods _does not need_.

**Comment by Re-VelatoR** [comment]
Yeah it's no rush. By just having the battery-powered items in a normal slot or somewhere on the ground/in the cabinet on the ship and returning to orbit at least once allows them to be recharged in the reserved slots for the remainder of the session.

Flip has a dedicated channel for the reserved slots mods in the Lethal Company modding discord, which is probably the best way to contact them about it.

**Comment by AndreyMrovol** [comment]
Yeah, i've already [contacted them 😅](https://discord.com/channels/1168655651455639582/1177039162428366848/1196759084423200768), will see what's their response.

In the meantime: I think i've found a workaround (and potentially improvement) to the whole process: instead of scanning the ship and players for items, just charge **all** existing items 😆

![image](https://github.com/AndreyMrovol/LethalOrbitRecharge/assets/32998721/ec940a0a-1d6e-47eb-a855-97ef60eee833)

**Comment by AndreyMrovol** [comment]
I've pushed v0.0.3, which should fix your issue @Re-VelatoR, please try it and let me know.

**Comment by Re-VelatoR** [comment]
Apologies for taking so long to get back to you. Working perfect now, thank you kindly!
